export const produtos = [
  {
    id: 1,
    nome: "Pizza de Pepperoni",
    descricao: "Deliciosa pizza com molho de tomate, queijo e pepperoni.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 285,
      carboidratos: 36,
      proteina: 12,
      gordura: 11,
      fibra: 2,
    },
    ingredientes: ["Massa de pizza", "Molho de tomate", "Queijo", "Pepperoni"],
    nota: 8.5,
    categoria: "Pizza",
    alergicos: ["Contém glúten", "Contém lactose"],
  },
  {
    id: 2,
    nome: "Hambúrguer Clássico",
    descricao:
      "Hambúrguer suculento com carne, alface, queijo e molho especial.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 450,
      carboidratos: 30,
      proteina: 25,
      gordura: 28,
      fibra: 2,
    },
    ingredientes: [
      "Pão de hambúrguer",
      "Carne moída",
      "Alface",
      "Queijo",
      "Molho especial",
    ],
    nota: 9.2,
    categoria: "Hambúrguer",
    alergicos: ["Contém glúten", "Contém lactose"],
  },
  {
    id: 3,
    nome: "Sushi Variado",
    descricao: "Seleção de sushi fresco, incluindo sashimi, nigiri e rolos.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 320,
      carboidratos: 45,
      proteina: 12,
      gordura: 9,
      fibra: 3,
    },
    ingredientes: [
      "Arroz de sushi",
      "Peixe fresco",
      "Alga nori",
      "Legumes",
      "Molho de soja",
    ],
    nota: 9.8,
    categoria: "Sushi",
    alergicos: ["Contém peixe", "Contém soja"],
  },
  {
    id: 4,
    nome: "Salada Caesar",
    descricao: "Salada de alface romana com croutons, parmesão e molho Caesar.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 180,
      carboidratos: 12,
      proteina: 5,
      gordura: 14,
      fibra: 3,
    },
    ingredientes: [
      "Alface romana",
      "Croutons",
      "Queijo parmesão",
      "Molho Caesar",
    ],
    nota: 7.6,
    categoria: "Salada",
    alergicos: ["Contém glúten", "Contém lactose"],
  },
  {
    id: 5,
    nome: "Taco de Carnitas",
    descricao:
      "Taco mexicano recheado com carne de porco desfiada e guacamole.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 320,
      carboidratos: 25,
      proteina: 18,
      gordura: 20,
      fibra: 4,
    },
    ingredientes: [
      "Tortilla de milho",
      "Carne de porco desfiada",
      "Guacamole",
      "Salsa",
    ],
    nota: 8.3,
    categoria: "Taco",
    alergicos: ["Contém milho", "Contém carne de porco"],
  },
  {
    id: 6,
    nome: "Massa Carbonara",
    descricao:
      "Massa italiana com bacon, ovos, queijo parmesão e pimenta preta.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 520,
      carboidratos: 45,
      proteina: 15,
      gordura: 30,
      fibra: 2,
    },
    ingredientes: ["Massa de espaguete", "Bacon", "Ovos", "Queijo parmesão"],
    nota: 8.7,
    categoria: "Massa",
    alergicos: ["Contém glúten", "Contém ovos"],
  },
  {
    id: 7,
    nome: "Sorvete de Baunilha",
    descricao: "Sorvete cremoso de baunilha com cobertura de chocolate.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 250,
      carboidratos: 30,
      proteina: 3,
      gordura: 15,
      fibra: 1,
    },
    ingredientes: ["Sorvete de baunilha", "Cobertura de chocolate"],
    nota: 9.0,
    categoria: "Sobremesa",
    alergicos: ["Contém lactose"],
  },
  {
    id: 8,
    nome: "Frango Frito Crocante",
    descricao: "Frango frito dourado e crocante com batata frita.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 600,
      carboidratos: 40,
      proteina: 35,
      gordura: 35,
      fibra: 3,
    },
    ingredientes: ["Frango frito", "Batata frita"],
    nota: 7.8,
    categoria: "Frango",
    alergicos: ["Contém glúten"],
  },
  {
    id: 9,
    nome: "Torta de Maçã Caseira",
    descricao: "Torta de maçã feita com maçãs frescas e canela.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 280,
      carboidratos: 40,
      proteina: 2,
      gordura: 14,
      fibra: 4,
    },
    ingredientes: ["Maçãs frescas", "Canela", "Massa de torta"],
    nota: 8.9,
    categoria: "Torta",
    alergicos: ["Contém glúten"],
  },
  {
    id: 10,
    nome: "Café Espresso Duplo",
    descricao: "Café espresso duplo com creme espesso e aroma intenso.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 5,
      carboidratos: 0,
      proteina: 1,
      gordura: 0,
      fibra: 0,
    },
    ingredientes: ["Café espresso"],
    nota: 9.8,
    categoria: "Café",
    alergicos: ["Contém cafeína"],
  },
  {
    id: 11,
    nome: "Sanduíche de Frango Grelhado",
    descricao: "Sanduíche de frango grelhado com alface, tomate e maionese.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 320,
      carboidratos: 35,
      proteina: 20,
      gordura: 12,
      fibra: 3,
    },
    ingredientes: [
      "Pão de sanduíche",
      "Frango grelhado",
      "Alface",
      "Tomate",
      "Maionese",
    ],
    nota: 8.2,
    categoria: "Sanduíche",
    alergicos: ["Contém glúten", "Contém ovos"],
  },
  {
    id: 12,
    nome: "Sopa de Tomate Cremosa",
    descricao: "Sopa de tomate com creme e croutons crocantes.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 180,
      carboidratos: 20,
      proteina: 2,
      gordura: 10,
      fibra: 3,
    },
    ingredientes: ["Tomates", "Creme", "Croutons"],
    nota: 7.0,
    categoria: "Sopa",
    alergicos: ["Contém glúten", "Contém lactose"],
  },
  {
    id: 13,
    nome: "Ceviche de Peixe Fresco",
    descricao: "Ceviche refrescante de peixe fresco com limão e coentro.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 150,
      carboidratos: 10,
      proteina: 20,
      gordura: 5,
      fibra: 2,
    },
    ingredientes: ["Peixe fresco", "Limão", "Coentro"],
    nota: 9.7,
    categoria: "Ceviche",
    alergicos: ["Contém peixe"],
  },
  {
    id: 14,
    nome: "Torta de Frutas Tropicais",
    descricao: "Torta de frutas tropicais frescas com creme de baunilha.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 230,
      carboidratos: 30,
      proteina: 3,
      gordura: 11,
      fibra: 4,
    },
    ingredientes: ["Frutas tropicais", "Creme de baunilha", "Massa de torta"],
    nota: 8.4,
    categoria: "Torta",
    alergicos: ["Contém glúten", "Contém lactose"],
  },
  {
    id: 15,
    nome: "Panquecas com Xarope de Maple",
    descricao: "Panquecas fofas cobertas com xarope de bordo puro.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 350,
      carboidratos: 45,
      proteina: 5,
      gordura: 15,
      fibra: 2,
    },
    ingredientes: ["Panquecas", "Xarope de bordo"],
    nota: 5.5,
    categoria: "Panquecas",
    alergicos: ["Contém glúten"],
  },
  {
    id: 16,
    nome: "Molho de Espaguete à Bolonhesa",
    descricao: "Molho de carne à bolonhesa rico com massa de espaguete.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 240,
      carboidratos: 25,
      proteina: 14,
      gordura: 10,
      fibra: 3,
    },
    ingredientes: ["Carne à bolonhesa", "Massa de espaguete"],
    nota: 8.6,
    categoria: "Massa",
    alergicos: ["Contém glúten"],
  },
  {
    id: 17,
    nome: "Sanduíche Vegetariano",
    descricao: "Sanduíche vegetariano com abacate, tomate e queijo derretido.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 320,
      carboidratos: 30,
      proteina: 8,
      gordura: 18,
      fibra: 6,
    },
    ingredientes: ["Pão de sanduíche", "Abacate", "Tomate", "Queijo derretido"],
    nota: 8.0,
    categoria: "Sanduíche",
    alergicos: ["Contém glúten", "Contém lactose"],
  },
  {
    id: 18,
    nome: "Tapioca Recheada",
    descricao: "Tapioca recheada com coco ralado e leite condensado.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 220,
      carboidratos: 35,
      proteina: 2,
      gordura: 7,
      fibra: 3,
    },
    ingredientes: ["Tapioca", "Coco ralado", "Leite condensado"],
    nota: 8.3,
    categoria: "Sobremesa",
    alergicos: ["Contém lactose", "Pode conter traços de amendoim"],
  },
  {
    id: 19,
    nome: "Bolo de Chocolate Triplo",
    descricao:
      "Bolo de chocolate triplo com camadas de chocolate e cobertura de ganache.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 380,
      carboidratos: 45,
      proteina: 5,
      gordura: 20,
      fibra: 2,
    },
    ingredientes: ["Bolo de chocolate", "Cobertura de ganache"],
    nota: 9.4,
    categoria: "Sobremesa",
    alergicos: ["Contém glúten", "Pode conter traços de leite"],
  },
  {
    id: 20,
    nome: "Sushi de Salmão Fresco",
    descricao:
      "Sushi de salmão fresco e saboroso com wasabi e gengibre em conserva.",
    image:
      "https://storage.googleapis.com/proudcity/mebanenc/uploads/2021/03/placeholder-image.png",
    tabelaNutricional: {
      calorias: 280,
      carboidratos: 40,
      proteina: 13,
      gordura: 8,
      fibra: 2,
    },
    ingredientes: [
      "Arroz de sushi",
      "Salmão fresco",
      "Wasabi",
      "Gengibre em conserva",
    ],
    nota: 6.5,
    categoria: "Sushi",
    alergicos: ["Pode conter traços de peixe cru"],
  },
];
